baseURL = 'https://example.com/'
languageCode = 'en-us'
title = 'Your Site Title'
theme = 'your-theme' # replace with your theme name
hasCJKLanguage = true
enableEmoji = true

# Build settings
buildFuture = true
buildDrafts = false
timeZone = 'Asia/Shanghai'

# Basic configuration
[pagination]
  pagerSize = 10

[params]
  description = "Short description of your site"
  author = "Your Name"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = false
  mermaid = true
  hasCJKLanguage = true
  ReadingTimeCharPerMin = 180
  disableSpecial1stPost = true

[params.homeInfoParams]
  Title = "👋 Welcome"
  Content = """
  Intro text for your homepage.
  """

[[params.socialIcons]]
  name = "email"
  url = "mailto:you@example.com"

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]

# Syntax highlighting
[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    style = "github-dark"

  [markup.goldmark.renderer]
    unsafe = true  # Allow HTML

  [markup.goldmark.extensions]
    typographer = false
    linkify = true
    strikethrough = true
    table = true
    taskList = true
  [markup.goldmark.parser]
    attribute = true


