baseURL = 'https://train.sh/'
languageCode = 'en-us'
title = 'Welcome to train.sh'
theme = 'hugo-trainsh'

# Build settings
buildFuture = true
buildDrafts = false
timeZone = 'Asia/Shanghai'

# URL normalization
disablePathToLower = false
removePathAccents = true
preserveTaxonomyNames = false

[pagination]
  pagerSize = 10

[params]
  description = "This blog covers artificial intelligence, productivity, and life insights."
  author = "Binbin Shen"
  mainSections = ["posts"]

[params.home]
  intro = """👋 Welcome! This is a personal blog where I document my learning journey in artificial intelligence, productivity, and record my thoughts on technology and life. Nothing groundbreaking here, just notes and reflections."""

[params.home.tags]
# Set to 0 or negative to show all tags
limit = 15
showCount = true

[params.home.recent]
limit = 5
moreText = "View all posts"

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    identifier = "home"
    weight = 10

  [[menu.main]]
    name = "Archive"
    pageRef = "/archive"
    identifier = "archive"
    weight = 20
  
  [[menu.main]]
    name = "Tags"
    pageRef = "/tags"
    identifier = "tags"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.goldmark.parser.attribute]
block = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    # Enable line numbers and render them in a table
    lineNos = true
    lineNumbersInTable = true
    anchorLineNos = false
    codeFences = true
    lineNoStart = 1
    noClasses = true
