name: Deploy Blog (see deploy-example.yml)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: echo "This is a placeholder. See .github/workflows/deploy-example.yml for Cloudflare Pages deployment."
