name: Deploy Blog (disabled on main)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: echo "Main branch is engine-only. Use trainsh branch for deployments."
