name: Deploy Blog

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Update submodules to latest
      run: |
        git submodule update --init --remote

    - name: Download hugo-trainsh theme
      run: |
        mkdir -p themes
        if [ ! -d themes/hugo-trainsh ]; then
          echo "hugo-trainsh theme not found. Cloning..."
          git clone --depth=1 https://github.com/binbinsh/hugo-trainsh.git themes/hugo-trainsh
        else
          echo "hugo-trainsh theme already present."
        fi

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup uv
      uses: astral-sh/setup-uv@v3

    - name: Cache dependencies (uv)
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/uv
          ~/.cache/pip
        key: ${{ runner.os }}-uv-${{ hashFiles('**/requirements.txt') }}

    - name: Install dependencies (uv)
      run: |
        uv venv --python 3.10
        source .venv/bin/activate
        uv pip install -r requirements.txt

    - name: Sync posts from Notion
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: |
        source .venv/bin/activate
        python scripts/notion_sync.py --clean

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build Hugo site
      run: hugo --minify

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy ./public --project-name ${{ vars.CLOUDFLARE_PAGES_PROJECT }} --branch ${{ github.ref_name }}
