# This is an example workflow showing how to deploy to Cloudflare Pages.
# It is DISABLED by default (manual only). To enable automatic deploys,
# add push/schedule triggers under `on:` as shown in the comments below.

name: Deploy Example (Cloudflare Pages)

on:
  # Enable these when ready:
  # push:
  #   branches: [main]
  # schedule:
  #   - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies (uv)
        run: |
          uv venv --python 3.10
          uv pip install -r requirements.txt

      - name: Sync posts from Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          uv run scripts/notion_sync.py --clean

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./public --project-name ${{ vars.CLOUDFLARE_PAGES_PROJECT }} --branch ${{ github.ref_name }}


